# Generated by Django 2.1.7 on 2019-03-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190319_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=75)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_pub', models.DateTimeField(verbose_name='date published')),
                ('product_image', models.CharField(max_length=500)),
                ('product_description', models.CharField(max_length=150)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
    ]
